### ISSUE TITLE
`UnhandledPromiseRejectionWarning: Error: cannot estimate gas` when running `yarn demo:initialize --force`

### ISSUE THREAD

**Issue by ghost** [OffchainLabs/arbitrum-classic#1414] opened 2021-07-23 10:12 UTC
I'm trying to follow the instructions here: https://developer.offchainlabs.com/docs/local_blockchain
Unfortunately running `yarn demo:initialize` results in the following error:
```
% yarn demo:initialize --force           
yarn run v1.22.10
$ ts-node ./scripts/setup_validators_demo.ts init --force
No devnet privkey set
(node:34322) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Created rollup 0x2b39D5E8b1EFE16Fdb8ceD47c004733e345f4256
(node:34287) UnhandledPromiseRejectionWarning: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":69,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0x56bc75e2d63100000\",\"from\":\"0x81183c9c61bdf79db7330bbcda47be30c0a85064\",\"to\":\"0x2ac4b5573dbeb36092625a9895e5d6880623b470\",\"data\":\"0xad9d4ba3000000000000000000000000c7711f36b2c13e00821ffd9ec54b04a60aefbd1b\"}],\"id\":69,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:7545"}, method="estimateGas", transaction={"from":"0x81183C9C61bdf79DB7330BBcda47Be30c0a85064","to":"0x2Ac4b5573dBEB36092625a9895E5D6880623B470","value":{"type":"BigNumber","hex":"0x056bc75e2d63100000"},"data":"0xad9d4ba3000000000000000000000000c7711f36b2c13e00821ffd9ec54b04a60aefbd1b"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.0.24)
    at Logger.makeError (/home/ralf/arbitrum/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/home/ralf/arbitrum/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at checkError (/home/ralf/arbitrum/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:68:16)
    at JsonRpcProvider.<anonymous> (/home/ralf/arbitrum/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:463:20)
    at step (/home/ralf/arbitrum/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/ralf/arbitrum/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/ralf/arbitrum/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eigmax** [comment] 2021-08-02 02:54
Can you plz set the  `packages/arb-bridge-eth/scripts/launch-geth` with flag `--verbosity=4` so you can see why the transaction reverted. I think the error you see is not the root cause.

**Comment by eigmax** [comment] 2021-08-02 04:48
@hkalodner  Can you help to take a look this issue?  I also meet same issue on commit ` 69c58d6b33c4dfb7d8293ccfdcb1675798201b7e`

**Comment by eigmax** [comment] 2021-08-02 09:19
Fixed by limit the gas for depositEth in packages/tools/scripts/setup_validators_demo.ts
```
+++ b/packages/tools/scripts/setup_validators_demo.ts
@@ -29,6 +29,7 @@ async function setupRollup(
     `yarn workspace arb-bridge-eth hardhat create-chain --sequencer ${sequencerAddress} --network ${network}`
   )

   const fileName = `rollup-${network}.json`
   const file = fs.readFileSync(`../arb-bridge-eth/${fileName}`).toString()
   const ev = JSON.parse(file)
@@ -69,7 +70,7 @@ async function initializeClientWallets(inboxAddress: string): Promise<void> {
   const amount = ethers.utils.parseEther('100')

   for (const address of addresses) {
-    await inbox.depositEth(address, { value: amount })
+    await inbox.depositEth(address, { value: amount, gasLimit:  964661-1 })
   }
 }
```

**Closed** 2023-05-29 17:26 UTC
